### PR TITLE
Transition to cmake

### PR DESCRIPTION
**Pull request by l3u**
I think it's better to create a pull request for this, as discussing there will also track further commits.

### CODE REVIEW

**Comment by hmueller01** [comment]
Compiles on MacOSX 10.11 with cmake from homebrew. -> confirmed
Maybe probonopd can confirm for openwrt:
[https://github.com/probonopd/vcontrold-for-openwrt](https://github.com/probonopd/vcontrold-for-openwrt)

**Comment by hmueller01** [comment]
Hi,
can you please add a README.md to explain how the build process is done. You have written it before somewhere but I can't find it any more.
Most important for me is a note, how to change the install path without changing  CMakeLists.txt:
`cmake -DCMAKE_INSTALL_PREFIX=/usr/local ..`
Tx

**Comment by l3u** [comment]
Here you go.

**Comment by hmueller01** [comment]
Tx. But I find it more convenient to set the install prefix more permanent, instead of giving the path to every make install. I would never install a self compiled code to /usr. /usr holds only installed packages (using e.g. apt-get). Everything else belongs to /usr/local or /opt ...
So for me it would be nice, it you could also add 

> If you want to install the package with another prefix, use
>` make DESTDIR=<PREFIX> install`
> or
> `cmake -DCMAKE_INSTALL_PREFIX=<PREFIX> ..`
>

**Comment by l3u** [comment]
Well, I come from Gentoo, all our code is self-compiled ;-) But of course, you can tell cmake directly about another prefix.

**Comment by speters** [comment]
Thx, cmake is now merged into master.

Most of the legacy-files have been removed to cut with old stuff.
These are now found in the "legacy" branch.

The build instructions formerly written in the short top-level README.md are now in doc/INSTALL.md

**Comment by l3u** [comment]
Nice :-)

**Pull request merged**
