### PR TITLE
Fix possible problems detected via CodeQL codescanning workflow

### PR DESCRIPTION
**Pull request by speters**
This fixes possible problems being detected by the CodeQL codescanning workflow.

Problems contained:
  * 27 "Uncontrolled format string" (https://www.securecoding.cert.org/confluence/display/c/FIO30-C.+Exclude+user+input+from+format+strings) warnings which were caused by overly complicated use of `logIT()` function,
  * 2 "Time-of-check time-of-use filesystem race condition" (https://www.securecoding.cert.org/confluence/display/c/FIO01-C.+Be+careful+using+functions+that+use+file+names+for+identification) problems,
  * 1 "Likely overrunning write" problem caused by format string handling integer instead of char

Please be so kind as to test this version.

### CODE REVIEW

**Comment by hmueller01** [comment]
I think it is not good to merge a pull request right away. This way it is not possible to add more changes.
In many cases the reserved memory `char string[100];` is not needed any more. 
I'll pull the new master and test it. :-)

**Comment by hmueller01** [comment]
New version is running. I'll open a new PR to remove these unused string's ...

**Comment by speters** [comment]
I was solely concetrated on those easy fixes.
Shame on me. And thx for having an eye on it.

**Comment by hmueller01** [comment]
Until now it works like before. As it is already merged it can be released ;-)
Pls review #105 (I tested with this PR ...)

**Pull request merged**
