### PR TITLE
Build options

### PR DESCRIPTION
**Pull request by l3u**
This makes building of the `vsim` and `vclient` helper programs optional (`vclient` is built by default, `vsim` not – this seems to be some tool only for development, isn't it?)

Also, compilation of the manpages can be switched on and off now (so that somebody having the Docutils installed but not wanting the manpages won't get them).

Can be used as follows:
```
cmake -DVSIM=ON -DMANPAGES=OFF ..
```
would e. g. trigger the `vsim` program to be compiled along with `vcontrold` and `vclient`, but not the manpages.

### CODE REVIEW

**Comment by l3u** [comment]
What's that AppVeyor stuff btw? Tells me something about MSBuild and Visual Studio – we're on Linux here, aren't we?!

**Comment by speters** [comment]
Sorry for the Appveyor confusion. I registered for it to make it build for _Cygwin_ , but I didn't realise that it was enabled be default without having it configured properly. 
I spent quite a while to figure out how to cross-compile for Cygwin on a Linux host (and failed), then I realised that Appveyor has Cygwin.

My short-term plans are to supply auto-generated binary builds for often-requested platforms Linux/x86, Linux/armhf (Raspi), Cygwin via the deployment possibilites of Travis CI and the likes.

**Comment by l3u** [comment]
So … what do you think about this?

**Comment by speters** [comment]
Yes, might be a good thing too keep vsim out of a normal build. For vclient, is don't see any advantages, as it's currently a cheap build without new dependencies.

**Comment by hmueller01** [comment]
I do not see a real advantage. The build is so fast and the code is so small that it is not really worth it. But just my opinion.

**Comment by hmueller01** [comment]
One should add these switches to INSTALL.md (or somewhere else) that it is documented ...

**Comment by speters** [comment]
Good point, is documented now.

**Pull request merged**
